language: english.yml               #File to load for messages

group-containers: true               #Allows furnaces/dispensers to act like chests, one sign for all connected blocks

piston-protection: true             #Prevents doors and trapdoors from being broken

redstone-protection: true           #Denies redstone from toggling doors and trapdoors

enderman-protection: true           #Prevents endermen from breaking doors

explosion-protection: true          #Protect owned blocks from explosions
broadcast-tnt-fizzle: false         #For TNT, broadcast that it failed
broadcast-tnt-fizzle-radius: 25     #Radius in blocks to broadcast failure

#Standard multiplayer color scheme
#0 Black          6 Gold           c Red            
#1 Dark Blue      7 Gray           d Pink           
#2 Dark Green     8 Dark Gray      e Yellow         
#3 Teal           9 Blue           f White          
#4 Dark Red       a Bright Green   
#5 Purple         b Aqua           
default_color_private_line_1: 0     
default_color_private_line_2: 0     
default_color_private_line_3: 0     
default_color_private_line_4: 0     
default_color_moreusers_line_1: 0   
default_color_moreusers_line_2: 0   
default_color_moreusers_line_3: 0   
default_color_moreusers_line_4: 0   

default_door_timer: 0               #The delay after which a door will toggle again, 0 to disable

silent-door-sounds: false           #Gives normally silent doors the same effects as wooden ones
timed-door-sounds: false            #Gives timed doors the same effect as when opened, if silent, stays silent

clear-sign-selection: false         #Clear sign selection after using /deadbolt <line> <text>

vertical-trapdoors: false           #Related trapdoor groups travel vertically, in addition to horizontally

quick-signs: true                   #Allows right click placement of signs automatically on the target