name: DeadboltBridge_SimpleClans
main: com.daemitus.deadbolt.bridge.simpleclans.DeadboltBridge_SimpleClans
version: 1.0
author: daemitus
description: Bridge Deadbolt and SimpleClans for [ClanName] and [ClanTag] authorization on signs
depend: [Deadbolt, SimpleClans]