name: Lockette
main: org.yi.acru.bukkit.Lockette.Lockette
version: 1.3/1.4.4
author: Daemitus
description: This bridges all plugins that look for Lockette and substitutes Deadbolt
depend:
  - Deadbolt