name: Deadbolt-PermissionsEx
main: com.daemitus.deadbolt.bridge.permissionsex.PermissionsExBridge
version: 1.2
author: daemitus
description: Bridge Deadbolt and PermissionsEx for [GroupName] authorization on signs
softdepend: [Deadbolt, PermissionsEx]
#THIS SHOULD BE A HARD DEPEND. BUKKIT HAS AN ISSUE WITH CONFLICTING SOFT/HARD DEPENDENCIES