name: Deadbolt-SimpleClans
main: com.daemitus.deadbolt.bridge.simpleclans.SimpleClansBridge
version: 1.3/1.6
author: daemitus
description: Bridge Deadbolt and SimpleClans for [ClanName] and [ClanTag] authorization on signs
softdepend: [Deadbolt, SimpleClans]
#THIS SHOULD BE A HARD DEPEND. BUKKIT HAS AN ISSUE WITH CONFLICTING SOFT/HARD DEPENDENCIES