name: DeadboltBridge-SimpleClans
main: com.daemitus.deadbolt.bridge.simpleclans.DeadboltBridge_SimpleClans
version: 1.2
author: daemitus
description: Bridge Deadbolt and SimpleClans for [ClanName] and [ClanTag] authorization on signs
softdepend: [Deadbolt, SimpleClans]
#THIS SHOULD BE A HARD DEPEND. BUKKIT HAS AN ISSUE WITH CONFLICTING SOFT/HARD DEPENDENCIES