name: Deadbolt-Towny
main: com.daemitus.deadbolt.bridge.towny.TownyBridge
version: 1.3/0.76.1
author: daemitus
description: Bridge Deadbolt and Towny for [TownName] and [NationName] authorization on signs, optional restricting of usage in wilderness areas
softdepend: [Deadbolt, Towny]
#THIS SHOULD BE A HARD DEPEND. BUKKIT HAS AN ISSUE WITH CONFLICTING SOFT/HARD DEPENDENCIES
permissions:
    deadbolt.towny.wild.denyall:
        description: Denies protecting of objects in Towny wilderness areas
        default: false