name: DeadboltBridge_Towny
main: com.daemitus.deadbolt.bridge.towny.DeadboltBridge_Towny
version: 1.0
author: daemitus
description: Bridge Deadbolt and Towny for [TownName] and [NationName] authorization on signs
depend: [Deadbolt, Towny]