name: DeadboltBridge_PermissionsEx
main: com.daemitus.deadbolt.bridge.permissionsex.DeadboltBridge_PermissionsEx
version: 1.0
author: daemitus
description: Bridge Deadbolt and PermissionsEx for [GroupName] authorization on signs
depend: [Deadbolt, PermissionsEx]