name: Deadbolt-EssentialsGroupManager
main: com.daemitus.deadbolt.bridge.essentialsgroupmanager.EssentialsGroupManagerBridge
version: 1.3/1.1
author: daemitus
description: Bridge Deadbolt and EssentialsGroupManager for [GroupName] authorization on signs
softdepend: [Deadbolt, GroupManager]
#THIS SHOULD BE A HARD DEPEND. BUKKIT HAS AN ISSUE WITH CONFLICTING SOFT/HARD DEPENDENCIES