name: Lockette
main: com.daemitus.lockette.Lockette
version: 1.0
author: daemitus
description: A simple plugin for locking containers and doors without passwords or database files. Recreated from Acru's original plugin.
commands:
    lockette:
        description: Access to the Lockette plugin via commands.
